Repository wearefrank/ladybug-frontend, pull requests merged in 2024-12, with the labels that each got.

#803 Test with different Spring profiles (using --spec command line argument)
  .github/workflows/cypress.env.json.cicd
  .github/workflows/proxy.cicd.conf.json
  .github/workflows/testing.js.yml
  cypress/e2e/no-profile/1-first.spec.ts
  cypress/e2e/no-profile/copying.cy.ts
  cypress/e2e/no-profile/debug/aboutOpenedReports.cy.ts
  cypress/e2e/no-profile/debug/clickingInTableOpensReport.cy.ts
  cypress/e2e/no-profile/debug/custom-editor.cy.ts
  cypress/e2e/no-profile/debug/deleteReports.cy.ts
  cypress/e2e/no-profile/debug/fileupload.cy.ts
  cypress/e2e/no-profile/debug/filterTable.cy.ts
  cypress/e2e/no-profile/debug/labels.cy.ts
  cypress/e2e/no-profile/debug/refresh.cy.ts
  cypress/e2e/no-profile/debug/reportGenerator.cy.ts
  cypress/e2e/no-profile/debug/runningReports.cy.ts
  cypress/e2e/no-profile/debug/settings-component.cy.ts
  cypress/e2e/no-profile/debug/show-warnings-and-errors.cy.ts
  cypress/e2e/no-profile/debug/table.cy.ts
  cypress/e2e/no-profile/debug/toast.cy.ts
  cypress/e2e/no-profile/debug/transformation.cy.ts
  cypress/e2e/no-profile/keep_state.cy.ts
  cypress/e2e/no-profile/test/testtab.cy.ts
  cypress/e2e/storage-xml/1-pre-existing-report.spec.ts
Labels: automerge

#814 Dummy PR to see how the checks behave
  .github/workflows/testing.js.yml
Labels: automerge

#819 717 error message not shown in debug tab
  cypress/e2e/no-profile/debug/runningReports.cy.ts
  src/app/debug/debug.component.ts
  src/app/debug/table/table.component.html
Labels: bug

#817 Fix: download button on debug screen
  src/app/report/edit-display/edit-display.component.ts
Labels: bug

#822 Feat: add ladybug mascot to top right corner next to version
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
Labels: enhancement

#835 Code cleanup
  src/app/app.component.ts
  src/app/compare/compare-tree/compare-tree.component.ts
  src/app/debug/debug-tree/debug-tree.component.ts
  src/app/debug/filter-side-drawer/filter-side-drawer.component.ts
  src/app/debug/table/table-settings-modal/table-settings-modal.component.ts
  src/app/debug/table/table.component.ts
  src/app/report/edit-display/edit-display.component.ts
  src/app/report/edit-display/encoding-button/encoding-button.component.ts
  src/app/shared/components/metadata-table/metadata-table.component.ts
  src/app/shared/interfaces/base-report.ts
  src/app/shared/interfaces/report.ts
  src/app/shared/interfaces/test-list-item.ts
  src/app/shared/services/helper.service.ts
  src/app/shared/services/http.service.ts
  src/app/shared/services/tab.service.ts
  src/app/shared/util/update-report-util.ts
  src/app/test/test-settings-modal/test-settings-modal.component.ts
  src/app/test/test-table/test-table.component.ts
Labels: Style
